<?xml version="1.0" encoding="utf-8"?><Database Name="guzellik merkezi" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=NUR;Initial Catalog=&quot;guzellik merkezi&quot;;Integrated Security=True" SettingsObjectName="wProje._1.Properties.Settings" SettingsPropertyName="guzellik_merkeziConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CUSTOMER" Member="CUSTOMERs">
    <Type Name="CUSTOMER">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tcNo" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="bDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="job" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="phone" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="sex" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="regDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DATETIME" Member="DATETIMEs">
    <Type Name="DATETIME">
      <Column Name="num" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="custId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="serviceName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="time" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SERVICE" Member="SERVICEs">
    <Type Name="SERVICE">
      <Column Name="num" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="custId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="servName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="empName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="price" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
</Database>